---
collections:
  - name: ansible.posix
  - name: community.general
  - name: community.docker
  - name: community.crypto
  - name: ansible.netcommon
  - name: community.postgresql
  - name: community.mysql
  - name: community.aws # For AWS integrations
  - name: azure.azcollection # For Azure integrations
  - name: google.cloud # For GCP integrations

roles:
  - name: geerlingguy.docker
  - name: geerlingguy.nginx
  - name: geerlingguy.postgresql
